import Link from "next/link";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="fixed top-0 left-0 right-0 z-10 bg-background/80 backdrop-blur-sm border-b border-card-border">
        <div className="max-w-3xl mx-auto px-4 py-3 flex items-center justify-between">
          <Link
            href="/"
            className="text-xl font-bold text-foreground flex items-center gap-2 hover:opacity-80 transition-opacity"
          >
            <span className="text-2xl">✨</span>
            BetterEnglish
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 pt-24 pb-12">
        <h1 className="text-3xl font-bold text-foreground mb-8">
          Privacy Policy
        </h1>

        <div className="prose prose-gray dark:prose-invert max-w-none space-y-6 text-foreground/80">
          <p className="text-sm text-foreground/60">
            Last updated: December 7, 2024
          </p>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">
              1. Introduction
            </h2>
            <p>
              BetterEnglish (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is committed to protecting your privacy.
              This Privacy Policy explains how we collect, use, and safeguard your information
              when you use our text improvement service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">
              2. Information We Collect
            </h2>
            <h3 className="text-lg font-medium text-foreground">
              Account Information
            </h3>
            <p>When you sign in using Google or GitHub, we collect:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Your email address</li>
              <li>Your name (as provided by the authentication provider)</li>
            </ul>

            <h3 className="text-lg font-medium text-foreground">
              Usage Information
            </h3>
            <p>When you use our service, we collect:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>The text you submit for improvement</li>
              <li>The improved text generated by our service</li>
              <li>Timestamps of your requests</li>
              <li>IP addresses for analytics purposes</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">
              3. How We Use Your Information
            </h2>
            <p>We use your information to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Provide and improve our text improvement service</li>
              <li>Save your request history (for logged-in users)</li>
              <li>Remember your preferences</li>
              <li>Analyze usage patterns to improve our service</li>
              <li>Communicate with you about service updates</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">
              4. Third-Party Services
            </h2>
            <p>We use the following third-party services:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                <strong>Google OAuth:</strong> For authentication. Google&apos;s privacy policy
                applies to the authentication process.
              </li>
              <li>
                <strong>GitHub OAuth:</strong> For authentication. GitHub&apos;s privacy policy
                applies to the authentication process.
              </li>
              <li>
                <strong>OpenAI:</strong> To process and improve your text. The text you submit
                is sent to OpenAI&apos;s API for processing.
              </li>
              <li>
                <strong>Supabase:</strong> For data storage and authentication management.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">
              5. Data Storage and Security
            </h2>
            <p>
              Your data is stored securely using Supabase, which provides enterprise-grade
              security. We implement appropriate technical and organizational measures to
              protect your personal information against unauthorized access, alteration,
              disclosure, or destruction.
            </p>
            <p>
              For anonymous users, text content is stored temporarily and automatically
              deleted after 30 days. Logged-in users can delete their history at any time.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">
              6. Your Rights
            </h2>
            <p>You have the right to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Access your personal data</li>
              <li>Delete your account and associated data</li>
              <li>Clear your request history</li>
              <li>Opt out of data collection by not using the service</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">
              7. Cookies and Local Storage
            </h2>
            <p>
              We use browser local storage to save your preferences (such as theme and tone
              settings) and, for non-logged-in users, your request history. This data stays
              on your device and is not transmitted to our servers unless you create an account.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">
              8. Changes to This Policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of any
              changes by posting the new Privacy Policy on this page and updating the
              &quot;Last updated&quot; date.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-foreground">
              9. Contact Us
            </h2>
            <p>
              If you have any questions about this Privacy Policy, please contact us through
              the application or by visiting our website.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-card-border">
          <Link
            href="/"
            className="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-300"
          >
            &larr; Back to BetterEnglish
          </Link>
        </div>
      </main>
    </div>
  );
}
